// Small, friendly wordlist for locally-generated session aliases (stone/kara
// style). ~200 short, distinct, easy-to-say words. agent-relay's OWN list — no
// dependency on magic. Order is irrelevant (selection is by hash, not index).
export const WORDS = [
  "acorn", "agate", "alder", "amber", "ant", "arch", "ash", "aspen",
  "bark", "basil", "bay", "beam", "bear", "bee", "bell", "birch",
  "bison", "bloom", "bolt", "briar", "brook", "bud", "cactus", "cedar",
  "clay", "cliff", "cloud", "clove", "cobble", "comet", "coral", "cove",
  "crag", "crane", "creek", "crest", "crow", "cub", "dale", "dawn",
  "deer", "delta", "dew", "dove", "drift", "dune", "dusk", "eagle",
  "elk", "elm", "ember", "fawn", "fennel", "fern", "fig", "fin",
  "finch", "fjord", "flame", "flax", "flint", "foam", "fox", "frost",
  "gale", "gem", "ginger", "glade", "gold", "gorse", "grove", "gull",
  "harbor", "hare", "hawk", "hazel", "heath", "hen", "holly", "hops",
  "ibex", "iris", "ivy", "jade", "jay", "jet", "juniper", "kelp",
  "kite", "koi", "larch", "lark", "leaf", "ledge", "lichen", "lily",
  "lime", "linden", "lion", "loon", "lotus", "lynx", "mallow", "maple",
  "marsh", "mesa", "mint", "mist", "mole", "moon", "moor", "moss",
  "moth", "mound", "nest", "nettle", "newt", "nook", "nova", "oak",
  "oasis", "oat", "onyx", "opal", "orca", "otter", "owl", "palm",
  "peak", "pear", "pebble", "perch", "pike", "pine", "plum", "pond",
  "pony", "poppy", "puffin", "quail", "quartz", "quince", "rapid", "raven",
  "ray", "reed", "reef", "ridge", "robin", "rock", "rook", "root",
  "rose", "ruby", "rush", "rust", "sage", "salt", "sand", "seal",
  "sedge", "shell", "silk", "slate", "sleet", "snow", "sorrel", "spark",
  "spruce", "stork", "storm", "surf", "swan", "teak", "teal", "thaw",
  "thistle", "thorn", "tide", "toad", "topaz", "trout", "tulip", "twig",
  "vale", "vine", "violet", "vole", "walnut", "wasp", "wave", "wheat",
  "willow", "wisp", "wolf", "wren", "yarrow", "yew", "zephyr", "zinc",
];
